# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/Anvil

d-restore-cache: &d-restore-cache
    keys:
        -a2-dependencies-{{ checksum "/usr/bin/python2.7" }}
        -a2-dependencies-

d-update-git: &d-update-git
    name: update git
    command: |
        yum remove -y git
        yum install -y epel-release
        yum install -y https://centos6.iuscommunity.org/ius-release.rpm
        yum install -y git2u
        yum install -y python27
        mkdir ~/test-results

d-save_cache: &d-save-cache
    paths:
        - /usr/lib64/python2.7
        - /usr/lib/python2.7
        - /usr/include/python2.7
        - /usr/bin/python2.7
    key: a2-dependencies-{{ checksum "/usr/bin/python2.7" }}

d2-restore_cache: &d2-restore-cache
    keys:
        - a1-dependencies-{{ checksum "requirements.txt" }}
        - a1-dependencies-

d-set-up-mayapy: &d-set-up-mayapy
    name: set up mayapy and install deps
    command: make install-deps

d2-save-cache: &d2-save-cache
    paths:
      - ~/venv/
    key: a1-dependencies-{{ checksum "requirements.txt" }}

post-job: &post-job
    - store_test_results:
        path: ~/test-results

    - store_artifacts:
        path: ~/.anvil
        destination: ~/test-results

maya-2017-run: &maya-2017-run
    name: run tests
    command: |
        MAYA_VERSION=2017
        export MAYA_VERSION >> "$BASH_ENV"
        TEST_PATH=~/test-results
        export TEST_PATH >> "$BASH_ENV"
        make test-unit

maya-2017-upload: &maya-2017-upload
    name: upload coverage
    command: make upload-coverage

maya-2016-run: &maya-2016-run
    name: run tests
    command: |
        MAYA_VERSION=2015
        export MAYA_VERSION >> "$BASH_ENV"
        TEST_PATH=~/test-results
        export TEST_PATH >> "$BASH_ENV"
        make test-unit

maya-2015-run: &maya-2015-run
    name: run tests
    command: |
      MAYA_VERSION=2015
      export MAYA_VERSION >> "$BASH_ENV"
      TEST_PATH=~/test-results
      export TEST_PATH >> "$BASH_ENV"
      make test-unit

jobs:
  build:
    docker:
      - image: mottosso/maya:2017
    <<: *defaults
    steps:
      - restore-cache:
          *d-restore-cache
      - run:
          *d-update-git
      - save-cache:
          *d-save-cache
      - checkout
      - restore-cache:
          *d2-restore-cache
      - run:
          *d-set-up-mayapy
      - save-cache:
          *d2-save-cache
      - run:
          *maya-2017-run
      - run:
          *maya-2017-upload
    <<: *post-job

  maya2016:
    docker:
      - image: mottosso/maya:2016
    <<: *defaults
    steps:
      - restore-cache:
          *d-restore-cache
      - run:
          *d-update-git
      - save-cache:
          *d-save-cache
      - checkout
      - restore-cache:
          *d2-restore-cache
      - run:
          *d-set-up-mayapy
      - save-cache:
          *d2-save-cache
      - run:
          *maya-2016-run
    <<: *post-job

  maya2015:
    docker:
      - image: mottosso/maya:2015
    <<: *defaults
    steps:
      - restore-cache:
          *d-restore-cache
      - run:
          *d-update-git
      - save-cache:
          *d-save-cache
      - checkout
      - restore-cache:
          *d2-restore-cache
      - run:
          *d-set-up-mayapy
      - save-cache:
          *d2-save-cache
      - run:
          *maya-2015-run
    <<: *post-job

workflows:
  version: 2
  test_maya_versions:
    jobs:
      - build