# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      #- image: circleci/python:3.6.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: daemonecles/centos6-maya:2017

    working_directory: ~/Anvil

    steps:
      - run:
          name: update git and gcc and libpython path
          command: |
            yum remove -y git
            yum install -y epel-release
            yum install -y https://centos6.iuscommunity.org/ius-release.rpm
            yum install -y git2u
            yum install upgrade -y gcc gcc-c++
            echo '/usr/autodesk/maya2017/lib/' >> /etc/ld.so.conf
            ldconfig
            export PYTHONHOME=/usr/autodesk/maya2017
            export PATH=$PATH:$PYTHONHOME

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: set up mayapy
          command: |
            wget https://bootstrap.pypa.io/get-pip.py
            mayapy get-pip.py
            chmod -x $(find tests/ -name '*.py')

      - run:
          name: install dependencies
          command: |
            mayapy -m pip install -r requirements.txt
            mayapy -m pip install docker-compose coveralls

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run tests
          command: |
            mayapy -m nose --with-coverage --cover-package=anvil
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports
