# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/Anvil

upload-coverage: &upload-coverage
    name: upload coverage
    command: |
        yum install -y git
        make upload-coverage

default-run: &default-run
    steps:
        - checkout
        - restore-cache: &d2-restore-cache
            keys:
                - a1-dependencies-{{ checksum "requirements.txt" }}
                - a1-dependencies-
        - run: &d-set-up-mayapy
            name: set up mayapy and install deps
            command: make install-deps
        - save-cache: &d2-save-cache
            paths:
              - ~/venv/
            key: a1-dependencies-{{ checksum "requirements.txt" }}
        - run: &run-tests
            name: run tests
            command: make test-unit
        - store_test_results: &store-results
            path: ~/test-results
        - store_artifacts: &store-artifacts
            path: ~/.anvil
            destination: ~/test-results


jobs:
  build:
    docker:
      - image: daemonecles/anvil:maya2017
    <<: *defaults
    steps:
      - checkout
      - restore-cache:
          *d2-restore-cache
      - run:
          *d-set-up-mayapy
      - save-cache:
          *d2-save-cache
      - run:
          *run-tests
      - run:
          *upload-coverage
      - store_test_results:
          *store-results
      - store_artifacts:
          *store-artifacts

  maya2016:
    docker:
      - image: daemonecles/anvil:maya2016
    <<: *defaults
    <<: *default-run

  maya2015:
    docker:
      - image: daemonecles/anvil:maya2015
    <<: *defaults
    <<: *default-run


workflows:
  version: 2
  test_maya_versions:
    jobs:
      - build
      - maya2016:
          requires:
              - build
      - maya2015:
          requires:
              - build
