# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/Anvil
  steps:
      - restore_cache:
          keys:
              -a2-dependencies-{{ checksum "/usr/bin/python2.7" }}
              -a2-dependencies-

      - run:
          name: update git
          command: |
              yum remove -y git
              yum install -y epel-release
              yum install -y https://centos6.iuscommunity.org/ius-release.rpm
              yum install -y git2u
              yum install -y python27
              mkdir ~/test-results

      - save_cache:
          paths:
              - /usr/lib64/python2.7
              - /usr/lib/python2.7
              - /usr/include/python2.7
              - /usr/bin/python2.7
          key: a2-dependencies-{{ checksum "/usr/bin/python2.7" }}

      - checkout

      - restore_cache:
          keys:
              - a1-dependencies-{{ checksum "requirements.txt" }}
              - a1-dependencies-

      - run:
          name: set up mayapy and install deps
          command: make install-deps

      - save_cache:
          paths:
            - ~/venv/
          key: a1-dependencies-{{ checksum "requirements.txt" }}

      - run:  echo export TEST_PATH=~/test-results >> "$BASH_ENV"

post-job: &post-job
    - store_test_results:
        path: ~/test-results

    - store_artifacts:
        path: ~/.anvil
        destination: ~/test-results

jobs:
  build:
    docker:
      - image: mottosso/maya:2017
    <<: *defaults
      # run tests!
      - run:
          name: run tests
          command: |
            MAYA_VERSION=2017
            export MAYA_VERSION >> "$BASH_ENV"
            TEST_PATH=~/test-results
            export TEST_PATH >> "$BASH_ENV"
            make test-unit

      - run:
          name: upload coverage
          command: make upload-coverage
    <<: *post-job


  maya2016:
    docker:
      - image: mottosso/maya:2016
    <<: *defaults
      # run tests!
      - run:
          name: run tests
          command: |
            MAYA_VERSION=2015
            export MAYA_VERSION >> "$BASH_ENV"
            TEST_PATH=~/test-results
            export TEST_PATH >> "$BASH_ENV"
            make test-unit
    <<: *post-job

  maya2015:
    docker:
      - image: mottosso/maya:2015
    <<: *defaults
      # run tests!
      - run:
          name: run tests
          command: |
            MAYA_VERSION=2015
            export MAYA_VERSION >> "$BASH_ENV"
            TEST_PATH=~/test-results
            export TEST_PATH >> "$BASH_ENV"
            make test-unit
    <<: *post-job


workflows:
  version: 2
  test_maya_versions:
    jobs:
      - build