# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
# f
version: 2

defaults: &defaults
  working_directory: ~/Anvil

d2-restore_cache: &d2-restore-cache
    keys:
        - a1-dependencies-{{ checksum "requirements.txt" }}
        - a1-dependencies-

d-set-up-mayapy: &d-set-up-mayapy
    name: set up mayapy and install deps
    command: make install-deps

d2-save-cache: &d2-save-cache
    paths:
      - ~/venv/
    key: a1-dependencies-{{ checksum "requirements.txt" }}

maya-2017-run: &maya-2017-run
    name: run tests
    command: |
        MAYA_VERSION=2017
        export MAYA_VERSION >> "$BASH_ENV"
        make test-unit

maya-2016-run: &maya-2016-run
    name: run tests
    command: |
        MAYA_VERSION=2016
        export MAYA_VERSION >> "$BASH_ENV"
        make test-unit

maya-2015-run: &maya-2015-run
    name: run tests
    command: |
      MAYA_VERSION=2015
      export MAYA_VERSION >> "$BASH_ENV"
      make test-unit

upload-coverage: &upload-coverage
    name: upload coverage
    command: make upload-coverage

store-results: &store-results
    path: ~/test-results

store-artifacts: &store-artifacts
    path: ~/.anvil
    destination: ~/test-results


jobs:
  build:
    docker:
      - image: daemonecles/maya2017
    <<: *defaults
    steps:
      - restore-cache:
          *d-restore-cache
      - run:
          *d-update-git
      - save-cache:
          *d-save-cache

      - checkout

      - restore-cache:
          *d2-restore-cache
      - run:
          *d-set-up-mayapy
      - save-cache:
          *d2-save-cache
      - run:
          *maya-2017-run
      - run:
          *upload-coverage
      - store_test_results:
          *store-results
      - store_artifacts:
          *store-artifacts

  maya2016:
    docker:
      - image: daemonecles/maya2016
    <<: *defaults
    steps:
      - restore-cache:
          *d-restore-cache
      - run:
          *d-update-git
      - save-cache:
          *d-save-cache

      - checkout

      - restore-cache:
          *d2-restore-cache
      - run:
          *d-set-up-mayapy
      - save-cache:
          *d2-save-cache
      - run:
          *maya-2016-run
      - store_test_results:
          *store-results
      - store_artifacts:
          *store-artifacts

  maya2015:
    docker:
      - image: daemonecles/maya2015
    <<: *defaults
    steps:
      - restore-cache:
          *d-restore-cache
      - run:
          *d-update-git
      - save-cache:
          *d-save-cache

      - checkout

      - restore-cache:
          *d2-restore-cache
      - run:
          *d-set-up-mayapy
      - save-cache:
          *d2-save-cache
      - run:
          *maya-2015-run
      - store_test_results:
          *store-results
      - store_artifacts:
          *store-artifacts

workflows:
  version: 2
  test_maya_versions:
    jobs:
      - build