# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: mottosso/maya:2017

    working_directory: ~/Anvil

    steps:
      - run: make update-git

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - a1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - a1-dependencies-

      - run:
          name: set up mayapy and install deps
          command: make install-deps

      - save_cache:
          paths:
            - ~/venv/
          key: a1-dependencies-{{ checksum "requirements.txt" }}

      - run:  echo export TEST_PATH=~/test-results >> "$BASH_ENV"
      # run tests!
      - run:
          name: run tests
          command: |
            PYTHON_VERSION=26
            export PYTHON_VERSION >> "$BASH_ENV"
            TEST_PATH=~/test-results
            export TEST_PATH >> "$BASH_ENV"
            make test-unit

      - run:
          name: upload coverage
          command: make upload-coverage

      - store_test_results:
          path: ~/test-results

      - store_artifacts:
          path: ~/.anvil
          destination: ~/test-results

