from anvil.plugins.maya.dependencies import *
import anvil.plugins.base.api_proxy as api_proxy


@api_proxy.APIProxy._validate_function({"type": ["object", "null"],
                                        "properties": {
                                            "autoPriority": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "connectEffector": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "createCurve": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "createRootAxis": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "curve": {"type": "string"},
                                            "disableHandles": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "enableHandles": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "endEffector": {"type": "string"},
                                            "exists": {"type": "string"},
                                            "forceSolver": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "freezeJoints": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "jointList": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "name": {"type": "string"},
                                            "numSpans": {"type": "integer"},
                                            "parentCurve": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "positionWeight": {"type": "number"},
                                            "priority": {"type": "integer"},
                                            "rootOnCurve": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "rootTwistMode": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "setupForRPsolver": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "simplifyCurve": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "snapCurve": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "snapHandleFlagToggle": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "solver": {"type": "string"},
                                            "startJoint": {"type": "string"},
                                            "sticky": {"type": "string"},
                                            "twistType": {"type": "string"},
                                            "weight": {"type": "number"},
                                        },
                                        },
                                       API,
                                       'ikHandle')
def ik_handle(node, **kwargs):
    pass


@api_proxy.APIProxy._validate_function({"type": ["object", "null"],
                                        "properties": {
                                            "destinationSkin": {"type": "string"},
                                            "influenceAssociation": {"type": "string"},
                                            "mirrorInverse": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "mirrorMode": {"type": "string"},
                                            "noBlendWeight": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "noMirror": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "normalize": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "sampleSpace": {"type": "integer"},
                                            "smooth": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "sourceSkin": {"type": "string"},
                                            "surfaceAssociation": {"type": "string"},
                                            "uvSpace": {"type": "array", "items": {"type": "string"},
                                                        "minItems": 2, "maxItems": 2},
                                        },
                                        },
                                       API,
                                       'copySkinWeights')
def copy_skin_weights(source, destination, **kwargs):
    pass


@api_proxy.APIProxy._validate_function({"type": ["object", "null"],
                                        "properties": {
                                            "addInfluence": api_proxy.APIProxy.STR_TYPE,
                                            "addToSelection": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "after": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "afterReference": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "baseShape": api_proxy.APIProxy.STR_TYPE,
                                            "before": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "bindMethod": api_proxy.APIProxy.INT_TYPE,
                                            "deformerTools": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "dropoffRate": api_proxy.APIProxy.FLOAT_TYPE,
                                            "exclusive": api_proxy.APIProxy.STR_TYPE,
                                            "forceNormalizeWeights": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "frontOfChain": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "geometry": api_proxy.APIProxy.STR_TYPE,
                                            "geometryIndices": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "heatmapFalloff": api_proxy.APIProxy.FLOAT_TYPE,
                                            "ignoreBindPose": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "ignoreHierarchy": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "ignoreSelected": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "includeHiddenSelections": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "influence": api_proxy.APIProxy.STR_TYPE,
                                            "lockWeights": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "maximumInfluences": api_proxy.APIProxy.INT_TYPE,
                                            "moveJointsMode": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "name": api_proxy.APIProxy.STR_TYPE,
                                            "normalizeWeights": api_proxy.APIProxy.INT_TYPE,
                                            "nurbsSamples": api_proxy.APIProxy.INT_TYPE,
                                            "obeyMaxInfluences": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "parallel": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "polySmoothness": api_proxy.APIProxy.FLOAT_TYPE,
                                            "prune": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "recacheBindMatrices": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "remove": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "removeFromSelection": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "removeInfluence": api_proxy.APIProxy.STR_TYPE,
                                            "removeUnusedInfluence": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "selectInfluenceVerts": api_proxy.APIProxy.STR_TYPE,
                                            "skinMethod": api_proxy.APIProxy.INT_TYPE,
                                            "smoothWeights": api_proxy.APIProxy.FLOAT_TYPE,
                                            "smoothWeightsMaxIterations": api_proxy.APIProxy.INT_TYPE,
                                            "split": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "toSelectedBones": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "toSkeletonAndTransforms": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "unbind": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "unbindKeepHistory": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "useGeometry": api_proxy.APIProxy.BOOLEAN_TYPE,
                                            "volumeBind": api_proxy.APIProxy.FLOAT_TYPE,
                                            "volumeType": api_proxy.APIProxy.INT_TYPE,
                                            "weight": api_proxy.APIProxy.FLOAT_TYPE,
                                            "weightDistribution": api_proxy.APIProxy.INT_TYPE,
                                            "weightedInfluence": api_proxy.APIProxy.BOOLEAN_TYPE,

                                        },
                                        },
                                       API,
                                       'skinCluster')
def skin_cluster(objects):
    pass
