version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    api:
        format: "%(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: anvil_info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    dcc_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: anvil_dcc.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    testing_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: anvil_testing.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    api_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: api
        filename: anvil_api_calls.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    anvil:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

    anvil.log:
        level: INFO
        handlers: [console]
        propagate: no

    anvil.plugins.base.api_proxy:
        level: INFO
        handlers: [dcc_file_handler]
        propagate: no

    anvil.plugins.base.api_proxy.api_calls:
        level: INFO
        handlers: [api_file_handler]
        propagate: no

    testing:
        level: INFO
        handlers: [testing_file_handler]
        propagate: yes

root:
    level: INFO
    handlers: [console]
