version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(message)s"
    api:
        format: "%(message)s"
    structlog:
        format: "%(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: structlog
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: structlog
        filename: session.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    anvil:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

    anvil.log:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

    anvil.grouping.base:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

    anvil.grouping.rig:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

    anvil.grouping.sub_rig:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

    anvil.plugins.base.api_proxy:
        level: DEBUG
        handlers: [info_file_handler]
        propagate: yes

    anvil.plugins.base.api_proxy.api_calls:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

    anvil.tests:
        level: INFO
        handlers: [info_file_handler]
        propagate: yes

root:
    level: INFO
    handlers: [console]
